# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIdentificacion', models.CharField(max_length=20, verbose_name='No. de Identificaci\xf3n')),
                ('PPrimerNombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('PSegundoNombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('PPrimerApellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('PSegundoApellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('PEmail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('PTelefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono')),
                ('PCelular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('PEmpresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('PFacebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('PTwitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('PCargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo')),
                ('POrganizacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organizaci\xf3n')),
            ],
        ),
    ]
